---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-autoscaler-metal3-crd
rules:
- apiGroups:
  - "infrastructure.cluster.x-k8s.io"
  resources:
  - metal3machines
  - metal3machinetemplates
  - metal3datatemplates
  - machinedeployments
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - "storage.k8s.io"
  resources:
  - volumeattachments
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-autoscaler-metal3-crd-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-autoscaler-metal3-crd
subjects:
- kind: ServiceAccount
  name: cluster-autoscaler-clusterapi-cluster-autoscaler
  namespace: kube-system

