apiVersion: apps/v1
kind: Deployment
metadata:
  name: high-load-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: high-load
  template:
    metadata:
      labels:
        app: high-load
    spec:
      containers:
      - name: high-load-container
        image: nginx
        resources:
          requests:
            cpu: "1"
            memory: "512Mi"
